### ISSUE TITLE
Routing methodologies

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#24]
Right now, Skynet chooses a simple route randomly.  May be very useful to choose routes other ways... perhaps by using a data center metric that gives affinity to closer nodes?  More thought required on this.

**Comment by cdunn2001** [comment]
Oh. Now I see why it's scalable. Instead of a central [ESB](http://en.wikipedia.org/wiki/Enterprise_service_bus), the logic for finding the next service pipe is compiled into each initiator. If we refer to a central server at any time, we lose all scalability, so this is the essential step.

However, since it is compiled into each initiator, with doozer we can replace each initiator one-at-a-time when we want to change the algorithm. Pretty sweet.

Am I understanding it properly?

**Comment by bketelsen** [comment]
That's almost right.  The Initiator knows the service name it will be routing to.  So it asks Doozer for a router that provides that routing service.

**Comment by bketelsen** [comment]
But you have the principle right. No centralized servers, even Doozer can have many masters.  Skynet was designed specifically to cross data centers.

**Comment by cdunn2001** [comment]
I see how it can cross data-centers, but why query doozer? I thought doozer was just for config management. Why not get the entire list from doozer now and then, to avoid central interaction.

Even if doozer "has many masters", calling doozer each time must go through something central, no?

**Comment by bketelsen** [comment]
I'm sorry, didn't mean to muddy the original point - you're right we don't query Doozer every time.  But I was saying that even doozer isn't a single point of failure or scalability risk.  Doozer config changes are pushed to each node in the mesh, so there isn't any querying happening, it's all push.
