### ISSUE TITLE
Service Admin

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#52]
Start, Stop, Restart, Deregister services from sky command line interface.

**Comment by skelterjohn** [comment]
A note here before it slips my mind: perhaps the Deregister function should only return once all current requests have completed.

**Comment by bketelsen** [comment]
makes good sense.

**Comment by skelterjohn** [comment]
I have built into services an admin RPC server using the bsonrpc package. Currently it has register and unregister functions that appear to work.

At the moment, starting, stopping and restarting are done through interacting with the SkynetDaemon service (which is done with the sky command), rather than the admin rpc server.

**Comment by erikstmartin** [comment]
Completed
