### ISSUE TITLE
Pluggable configuration storage

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#9]
Doozer is primary and makes most sense - but we should support some other options - via interface, selectable at generation time.  Redis is a good choice because it supports push on changes.  Others should be supported by implementing the interface.

**Comment by cdunn2001** [comment]
I just killed doozerd on my Mac. It was consuming 700 MB. Not good! I wasn't using it, so why did it chew up memory?

I am working on the interface for the config manager, and I thought I would use doozer's. However, the Wait() method returns a doozer.Event object. I'm not sure how to interface that. Is it possible?

```
type Event struct {
  // copied from doozer
  ...
}
type Config interface {
  // other methods are fine, but not Wait(): 
 Wait(glob string, rev int64) (ev Event, err os.Error)
}
var DC Config


config.go:100: cannot assign *doozer.Conn to DC (type Config) in multiple assignment:
    *doozer.Conn does not implement Config (wrong type for Wait method)
            have Wait(glob string, rev int64) (ev doozer.Event, err os.Error)
            want Wait(glob string, rev int64) (ev Event, err os.Error)
```

Do you have any idea how to get this interface to compile?

How certain are you that you want doozer? If not, we need to discuss the interface that you really want.

**Comment by bketelsen** [comment]
Go apps grab a big chunk of memory and never fully release it.  It's a known issue.  It won't grow, just doesn't release unused RAM.

The interface needs to be more broad.  Let me think about it over dinner.

**Comment by cdunn2001** [comment]
I meant to ask you about something else. I'm not sure of the intent here. It doesn't seem thread-safe, since the rev could change before Set() is called:

`
165     // Get the current revision number of the doozer "store".
166     rev, err := skylib.DC.Rev()
167     if err != nil {
168         log.Panic(err.String())
169     }
170 
171     // Set the contents of a file in the "store" to our JSON
172     // string, if the file has not been modified since rev.
173     filename := "/routes/" + sName
174     _, err = skylib.DC.Set(filename, rev, b)
175     if err != nil {
176         log.Panic(err.String())
177     }
`

**Comment by bketelsen** [comment]
This is a doozer idiom.  We're getting a rev from Doozer, then locking this document to that rev.  Any changes to that doc have to be saved at a later rev.  So it needs to be atomic at the document (route here) level.

**Comment by bketelsen** [comment]
I was thinking redis would be a very simple to implement config store.

**Comment by cdunn2001** [comment]
It creates another dependency though. I wish we had something pure-Go.

By the way, doozer consumes only 50MB at invocation on my Mac. Its memory consumption seems to rise continually even when not in use. Maybe I had something set up wrong.

**Comment by bketelsen** [comment]
doozer just keeps adding memory as it runs until it hits its max.  Check the doozer list - there's a way to cap it.

**Comment by bketelsen** [comment]
There are some pure go KVStores out there on github.  I might have even opened a ticket last night suggesting we use zeroconf/mnds

**Comment by cdunn2001** [comment]
(From Brian's comment in a gist)

> Let's name the storage engine and the rpc protocol on the command line, but let sky lib pick the ports:
> 
> `./bin/myrouter --storage=doozer://192.168.228.1:6842 -protocol=rpc`
> `./bin/myrouter --storage=redis://192.168.228.1:6942 -protocol=json`
> 
> Skylib will then pick a random open port within a range and register with the storage engine. If we want named ports, we do that on the command line too
> 
> `./bin/myrouter --storage=doozer://192.168.228.1 -protocol=rpc -port=9001`
> 
> Every choice should have a default, and be over-rideable on the command line.
> 
> Defaults should be the fastest and most reliable - dozer and go's rpc

For the transport, I agree, since different servers could be using different transports. Skynet needs to support several all the time.

However, the Registry (doozer for now) is a singleton. Skynet will only use one at a time. If it supports several Registry implementations, then every Agent will link with all those unused libraries (doozer, reddis, etc.). That's bloat, extra link time, and most important, extra work just to get Skynet installed.

I think it's better to let the choice of Registry be taken at compile-time. Each back-end could have a Skynet plugin, wrapped by our registry API (a [Facade](http://en.wikipedia.org/wiki/Facade_pattern)), which would be imported by a generic name. Since GoLang does not provide a configuration system, that's a bit tricky. We cannot do this:

```
import "github.com/user/reddis_adaptor/skylib/registry"
```

That would hard-code the choice of implementation. Instead, we can do this:

```
import "skylib/registry"
```

Then, we would provide directions on how to install each adapter. E.g.

```
cd $GOROOT/src/pkg
git clone git:user/skynet-reddis-adapter/skylib/registry skylib/registry
goinstall skylib/registry
```

Each adapter would hard-code the path to the back-end, e.g.

```
// In the doozer adapter file, skylib/registry/registry.go
package skylib
import "github.com/ha/doozer"
```

That would automatically goinstall the back-end.

An alternative would be to store all the adapters in skylib, but without the `.go` extension. The user would then choose one and rename it. That would be easy, but maybe confusing and less flexible. I'm using this for now, with doozer's API, since that obviates the wrapper for doozer.

If you really want it your way -- the runtime option -- then we need a Registry "interface" for `DC`. (That's the [Adapter Pattern](http://en.wikipedia.org/wiki/Adapter_pattern), which differs from the Facade in that it's polymorphic.) Either way, we should think about what API we want for the Registry. We're using doozer's at the moment: https://gist.github.com/1125911

**Comment by bketelsen** [comment]
I'm probably too opinionated on this, but I really want a simple developer experience.  People who want to mess around with internals of Skynet can fork and change to their hearts' content.  Joe developer who may be relatively new to Go should be able to set a flag somewhere and rock on.

Let's build Doozer, and Redis into skylib and make them settable at runtime by a flag.

The other option - and I kind of like this too - is having multiple skylibs -- skylibredis skylibdoozer, etc.  Then skygen asks which to support and uses that as the import statement.

then we do all the abstraction in our multiple skylibs to get a single interface for skynet agents to use, and manage all the code sharing ourselves.  Skynet users simply goinstall one or both skylibs and link to the right one.

The changes that Christopher and Paulo have suggested over the past few days have been great from a usability front.  I think we're on a good path.

**Comment by cdunn2001** [comment]
I just pushed a branch called **store** to this repo. It does not alter any code, just new files.
- `store.go` is the interface. We will have to agree on the API. For now, it's a subset of doozer's.
- `fsstore.go` is my filesystem-based store, which uses `flocker`
- `flocker.go` uses `flock()` and `link()` for NFS-safe file-locking. It might go into a different package someday, but until the GoLang crew gets relative imports working, that's kind of a pain. (Same for the `rand` stuff.)

I suggest creating `mongo_store.go`, `redis_store.go`, etc. After I add `doozer_store.go`, which will be a doozer _adapter_ (necessary since `doozer.Event` is technically not the same type as the identical `skylib.Event`) we will let `DC` be the `Store` interface. Then we'll have run-time store selection.

**Comment by bketelsen** [comment]
awesome.

**Comment by cdunn2001** [comment]
`doozer_store.go` is done, in **store** branch. Take a look. You can work in that branch. It will merge back to **master** cleanly.

At some point, (unless we change the API) I will swap in doozer without the adapter, to check the speed penalty of the extra indirection. It's probably negligible, but with a new language it's worth checking.
